name: kaspa_dart
description: "A package for kaspa"
version: 0.0.1
homepage: "https://github.com/weishirongzhen/kaspa_dart"

environment:
  sdk: '>=3.4.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  decimal: ^3.0.2
  pointycastle: ^3.9.1
  hex: ^0.2.0
  crypto: ^3.0.5
  fixnum: ^1.1.0
  grpc: ^4.0.1
  collection: ^1.18.0
  fast_immutable_collections: ^10.2.4
  freezed_annotation: ^2.4.4
  http: ^1.2.2
  protobuf: ^3.1.0
  convert: ^3.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  freezed: ^2.5.2
  json_serializable: ^6.8.0

